(defun C:sumtext()

(princ "\n\ .... cargado ...")
(princ)
(princ (strcat "\nSuma de numeros en texto, Version 0.01, Copyright © 2011 by Ing. Marco Polo"))
(princ (strcat "\n..............Autocad 2010-2018............................................."))
(prompt "\n < Programa para realizar suma de valores en texto > ")
(prompt "\n Seleccione los elementos a sumar: ")
(setq  AL (ssget))
(setq  X 0)
(setq  J 0)
(setq  TOTAL 0)
(setq  CX1 0)
(setq  C (sslength AL))
(setq   CON C)
(while (/= X CON)
(setq  A (ssname AL X))
(setq  B (entget A))
(setq  D (assoc 1 B))
(setq  TEXT (CDR D))
(setq  NUMERO (atof TEXT))
(setq  EXPRE (strcat """(setq  cX1 NUMERO)"))
(eval (read EXPRE))
(setq  TOTAL (+ TOTAL CX1))
(setq  X (+ 1 X))
(setq  J (+ 1 J))
)

(setq  TOTA (rtos TOTAL))
(prompt "El total es = ")
(prompt TOTA)(terpri)

;(setq  P1 (GETPOINT " PUNTO DE INSERTCION: "))
;(COMMAND "TEXT" "S" "STANDARD" P1 "0.2" "0" TOTA) 

(prompt "\n Seleccione el texto a modificar: ")
(setq  mod1 (entsel))
(setq  m (entget (car mod1)))
(setq  mod (assoc 1 m))
(setq  check4 (cdr mod))
(setq  v4 (atof check4))
(setq  f (cons (car mod) TOTA))
(setq  g (subst f mod m))
(entmod g)

(PROMPT "\n .......Exit.........")

)